### ISSUE TITLE
Go 1.13 support

### ISSUE THREAD

**Issue by mvdan** [myitcv/gopherjs#49]
Given that this fork isn't merging with upstream anytime soon, I wonder if supporting 1.13 is planned :)

**Comment by myitcv** [comment]
Yeh - I'm going to need this at least for one of my repos.... I think the challenge will be getting the `internal/reflectlite` support working.

**Comment by paralin** [comment]
Getting some errors here... 

`myLocalVar$24ptr is not defined`

```go
var myLocalVar = MyType{}

var AddToLocalVar = myLocalVar.AddToLocalVar
```

**Comment by myitcv** [comment]
@paralin - I got an email notification on this thread about something you found not to be working. Have I got things mixed up or is everything sorted?

**Comment by paralin** [comment]
Yes, but I moved the issue to the main gopherjs repo since I discovered that it applies there too (against go 1.12)

**Comment by myitcv** [comment]
Ah I see it there now, thanks for pointing that out
